### ISSUE TITLE
sets-and-ranges: a mistake about regexp

### ISSUE THREAD

**Issue by FairyScript** [javascript-tutorial/en.javascript.info#1423]
[/9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md](https://github.com/javascript-tutorial/en.javascript.info/blob/master/9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md)

> Yes, because the regexp is **case-insensitive**, the pattern:`[^script]` part matches the character `"S"`.

I think there have a mistake, because the regexp is *case sensitivity*, not *case-insensitive*.

Looking forward any reply! 😃

**Comment by iliakan** [comment]
@paroche please take a look, do you understand the problem?

**Comment by paroche** [comment]
I think what the person meant to write is "is case sensitive" (As you probably already understand, "case sensitivity" is the quality of being sensitive to case -- "Q: What is the password's case sensitivity? A: It is case-sensitive".  And, though the usage is not too common, if something **has** case sensitivity, then it is case sensitive.). So they are disagreeing that the regexp is case-insensitive, saying instead that it is case-sensitive. Looking at the example, I'm inclined to agree -- if it were case-insensitive, the "s" would match the "S" and the ^ comparison would fail. So, if I understand correctly, it should read "because the regexp is case-sensitive" (meaning, e.g. "s" != "S").

**Comment by iliakan** [comment]
Right, thanks!

**Comment by iliakan** [comment]
Fixed.
