### ISSUE TITLE
Massive PR bot on ES   Files changed = 715

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#1930]
@iliakan 
I'm not a maintainer.   If it is not my place (you surely are busy) or if you already talked with our admin,  ignore & close this.

I thought update was a "stable maintainer" job.
Can I ask the criteria of the last PR ?

* javascript-translate-bot wants to merge 1,955 commits
* Files changed = 715 

It tries to replace ESP translations by the newer ENG ones.  Not easy to review.

Maybe the goal (a filter I didn't notice) is,  once done,
further PR would be only for ENG changes leaving ESP untouched.  Is that so?

**Comment by iliakan** [comment]
The PR is auto-generated from differences.

I believe, most of these changes are actually renamed/reorderings, while some refer to content, as EN was updated since the forking to ES.

I guess, the best way to fix a big difference is to manually compare the translations with originals, without the help of Git.

You can also ignore this PR and leave ES a bit outdated in some areas. There were no crucial changes.

**Comment by joaquinelio** [comment]
If it helps the tracking it would be nice,  once done keeping it updated is still hard without tracking. 
so just one question:
If we resolve leaving ESP version.  will next bot's PR ask for the same files? 

ha, not that I can figure how to do 715 conflicts before it.

**Comment by iliakan** [comment]
@joaquinelio Usually, there are not that many diversions, if the translation is kept up to date ;)

For this particular PR, I'd suggest to update the translation manually with git checkout --ours, as described in the PR (are you familiar with git?)

After pushing the merge, the new such PR will have a new starting point, so only the new differences will be addressed.

**Comment by iliakan** [comment]
P.S. Might be better to have this discussion in the ES repository, where you can also mention me as @iliakan.

**Comment by joaquinelio** [comment]
Ok I just saw you there.
