### ISSUE TITLE
imperfect knowledge

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#2025]
in this link
[function-prototype](https://javascript.info/function-prototype)

> Default F.prototype, constructor property
> Every function has the "prototype" property even if we don’t supply it.
> 
> The default "prototype" is an object with the only property constructor that points back to the function itself.

but when we try this code
`console.dir(Rabbit);`
We can see Rabbit.prototype has two property
`//__proto__` refers to empty object
`//Rabbit.prototype = {constructor, __proto__}`

**Comment by xxleyi** [comment]
@lumosmind `__proto__` is not Rabbit's own property, `__proto__` is on Object.

**Comment by lumosmind** [comment]
> @lumosmind `__proto__` is not `Rabbit.prototype`'s own property, `__proto__` is on `Object.prototype`.

please try this
```
function Rabbit() {}
console.dir(Rabbit);
console.dir(Rabbit.prototype.__proto__);
```

**Comment by xxleyi** [comment]
> > @lumosmind `__proto__` is not `Rabbit.prototype`'s own property, `__proto__` is on `Object.prototype`.
> 
> please try this
> 
> ```
> function Rabbit() {}
> console.dir(Rabbit);
> console.dir(Rabbit.prototype.__proto__);
> ```

you should use hasOwnProperty to test:

```
Rabbit.prototype.hasOwnProperty('__proto__')  // false
Object.prototype.hasOwnProperty('__proto__') // true
```

`Rabbit.prototype.__proto__ === Object.prototype` is `true`, think about it.

**Comment by lumosmind** [comment]
I got it by imagine something after your words. Maybe there can be more explanation about how `__proto__` and `[[Prototype]]` work. `__proto__` is getter/setter of "Object" but it gets/sets `[[Prototype]]` of object before dot.
```
const myRabbit = new Rabbit();
myRabbit.__proto__  = new shortEar();
```
`__proto__ `is getter/setter of "Object" but it sets [[Prototype]] of `myRabbit`.


on the other hand, Chrome gives this result
Is it kind of Chrome trick?

![Annotation 2020-07-25 011539](https://user-images.githubusercontent.com/12192118/88439632-6527db00-ce14-11ea-98c6-8d2f2c0ad0eb.png)

**Comment by xxleyi** [comment]
I used to struggle about this too and have got it, but I can not explain it easily in English. I will have a try.

When we talk about **prototype** in JS, we have two things: prototype object and prototype chain.

In default, All prototype objects are bound on **function constructors**, such as Function.prototype, Object.prototype, String.prototype. When we create a function, such as your Rabbit function, automatically we have a prototype object: Rabbit.prototype.

However, if we get an object, and we want to know those prototypes it inherits, we should use `__proto__`.

So, `__proto__` is handy for users to detect the prototype chain, but as you can see, it is confusing. Because the ability is put on Object.prototype, which will be inherited by all objects, which is the reason you can use Rabbit.prototype.__proto__.

But, why Chrome chooses to display it? I guess, because it is handy and useful.

And for clear this confusion, we have two new methods in ES5: `Reflect.getPrototypeOf() and Reflect.setPrototypeOf()`.

**Comment by lumosmind** [comment]
I appreciate your explanation. After sleeping a few hours and your new words, I got illuminated :)
Maybe chrome just want to say that "`__proto__` in the `Rabbit.prototype` means that result of  `Rabbit.prototype.__proto__` 
**calling getter** expression.  And inside of `Rabbit.prototype` is the best place to show that ,I think so.
