### ISSUE TITLE
DataTypes in JavaScript

### ISSUE THREAD

**Issue by GangulyRit** [javascript-tutorial/en.javascript.info#2061]
I read there are 8 data types. But now "null" is not a datatype. typeof(null) = "object" and "function" datatype has been introduced. This is as per latest ES 2020 form MDN and other resources studied. Correct me if I am wrong.

**Comment by iliakan** [comment]
null is a separate type, function isn't.

**Comment by GangulyRit** [comment]
![image](https://user-images.githubusercontent.com/44023607/90132316-32c22b80-dd8b-11ea-9c32-e91d400f48ed.png)

**Comment by iliakan** [comment]
Please don't hold me responsible for MDN errors. I'm just a man, can fix everything everywhere.

**Comment by getify** [comment]
https://github.com/mdn/mdn/issues/98#issuecomment-673513692

**Comment by iliakan** [comment]
@getify The word "type" has many meanings. Looks like the meaning that you choose differs from the meaning in the spec. 

That's surely an option.

I'd rather stick to the spec meaning though. When I hear other people talking about "types in JavaScript", they usually have the same meaning in mind, so that's it  🤷‍♂️
