### ISSUE TITLE
Suggestions on Array Methods article

### ISSUE THREAD

**Issue by MuhammedZakir** [javascript-tutorial/en.javascript.info#2148]
Array Methods article - https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/05-array-methods/article.md

1. We should mention about zero-based indices. Although it could be understood from reading the examples, I think it's better to explicitly mention it.
2. Most methods inside paragraphs are not wrapped in inline code. Methods inside inline code will be distinct from "normal text", making it easier to read/follow.

**Comment by iliakan** [comment]
1. Zero-based indices are mentioned in the previous article.
2. Send a PR please?

**Comment by tunggnu** [comment]
@MuhammedZakir I think you didn't read the actual article: [Array Methods](https://javascript.info/array-methods). You only read the [rendered version](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/05-array-methods/article.md) of the article on Github. But, Github can't render the external links like this `[arr.splice](mdn:js/Array/splice)`. That's why you see "most methods inside paragraphs are not wrapped in inline code."

@iliakan I think you can safely close this issue.
