### ISSUE TITLE
Somewhat misleading wording regarding JScript

### ISSUE THREAD

**Issue by ETCaton** [javascript-tutorial/en.javascript.info#2398]
In the [Manuals section](https://github.com/javascript-tutorial/en.javascript.info/blame/master/1-js/01-getting-started/2-manuals-specifications/article.md#L27), it states
> **MSDN** – Microsoft manual with a lot of information, including JavaScript (often referred to as JScript).

However JScript is an [alternative implementation of ECMAScript](https://en.wikipedia.org/wiki/JScript). Not sure if this is simplifying or unintentional, but I think it should be clearer on this distinction.

**Comment by MuhammedZakir** [comment]
They have archived JScript docs and also refers MDN. Maybe we should remove it? And if we are still mentioning it, we should use below link because it is hard to find the doc otherwise.

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/?redirectedfrom=MSDN
> This section provides developer information specific to Internet Explorer.
> 
> Information for Microsoft Edge can be found at [/microsoft-edge/](https://docs.microsoft.com/en-us/microsoft-edge/).
> 
> API reference and support information for both IE and Microsoft Edge can be found at MDN web docs.

---

> However JScript is an alternative implementation of ECMAScript. Not sure if this is simplifying or unintentional, but I think it should be clearer on this distinction.

Although technically that's the case, JScript is often considered as MS specific name to JavaScript and is used interchangeably. [1]

[1] https://en.wikipedia.org/wiki/JScript#Comparison_to_JavaScript

**Comment by iliakan** [comment]
Do you suggest to ditch the reference to MSDN totally, or modify it?

**Comment by MuhammedZakir** [comment]
> Do you suggest to ditch the reference to MSDN totally or to modify it?

Remove it. Microsoft has already moved to Edge and their doc is archived. The only reason to keep it is for IE, but even for that, you will get far better and "to the point" answer from other sites (like StackOverflow). I don't see any point in keeping it.
