### ISSUE TITLE
Addition operator anomaly 

### ISSUE THREAD

**Issue by rahulrajanpk** [javascript-tutorial/en.javascript.info#2505]
Its been a while since haven't gone through Chapter1(basic of Js) but I came across this anomaly of addition operator in JS. I request if we could add this as well in the tutorial

'1'+  +'2' 
3
'a'+  +1+'b' 
a1b

but
'a'+  +'a'+'b' 
aNaNb  //'a' is ignored

**Comment by tamiolaf** [comment]
Hi, this isn't an anomaly! This is expected behavior. The first `+` operator is a binary operator, which takes two inputs. The second `+` is an unary operator, which takes one input. The second `+` is executed first because the unary `+` has a higher priority than the binary `+`. It's a shorthand version of `Number()`, which converts values to integers.

**In the first example '1' + + '2'**
In this example, the string `'2'` is converted to the integer  `2` This leaves us with `'1'+2`. Both operands in a string concatenation must be converted to string before they're combined, so `2` is converted back to the string `'2'` and the result is `'12'`, not `3`

**In the second example 'a'+ +1+'b',** 
The same rules apply. The second `+` converts the `1` to an integer (nothing changes since it's already an integer), and appends it to a string after converting `1` to `'1'`. The value `'a1' + 'b'` is left, so the strings are appended and 'a1b' is returned.

**In the third example 'a'+ +'a'+'b'**
Once again, the second `+` tries to convert the second `'a'` to an integer. Since that value cannot be converted to a number, `NaN` is returned. If any of the operands is not a string, it must be converted to a string before it can be combined. So, `NaN` is converted to `'NaN'`. Then the same steps as above happen. The first two values are combined. Now we have `'aNaN' + 'b'`. These are both strings, so they're combined once more, returning `'aNaNb'`

You can find more detailed explanations about unary/binary operators and string concatenation here: https://javascript.info/operators
