### ISSUE TITLE
Wrong function/variable name in Class basics

### ISSUE THREAD

**Issue by Garbulix** [javascript-tutorial/en.javascript.info#2528]
Hi, I am currently learning JavaScript basics and i think there is a mistake in getters/setters in Class lesson.

```js
class User {

  constructor(name) {
    // invokes the setter
    this.name = name;
  }

  get name() {
    return this._name;
  }

  set name(value) {
    if (value.length < 4) {
      alert("Name is too short.");
      return;
    }
    this._name = value;
  }

}

let user = new User("John");
alert(user.name); // John

user = new User(""); // Name is too short.
```

Shouldn't there be `this._name = name;` in constructor?
I guess the `alert(user.name)` gets name from the variable directly, not from getter, which may be confusing to someone.

**Comment by Garbulix** [comment]
Sorry, I accidently clicked Enter and it created an issue. I am currently expanding my problem :D

**Comment by vsemozhetbyt** [comment]
`this._name = name;` in constructor would not trigger the `set name(value)` setter with its length check.

**Comment by ershad989** [comment]
@Garbulix when there’s a getter for a property in an object, accessing its value would be exclusively through the getter; the same thing applies for a setter ... the code should be exactly the way it is, because we want the initial setting of this to be though the setter hence follow the rules inside the setter

**Comment by Garbulix** [comment]
I think I understand now how it works. Thank you, @vsemozhetbyt and @ershad989 :)
