### ISSUE TITLE
Bosnian language translation

### ISSUE THREAD

**Issue by dejansdev** [javascript-tutorial/en.javascript.info#2765]
Language code: bs
Github nick: dejansdev
E-mail: dejansdev@gmail.com

**Comment by dotundefined** [comment]
@iliakan I am also interested in translation to Bosnian language. Challenge is, there is already a [repository](https://github.com/javascript-tutorial/bs.javascript.info) created with "bs" language code, but it has been abandoned more than a year ago.

Is it possible to delete that repository, and create a new one with the same name, so that the translation can be started from scratch without having to check all the translation that is done so far? 

I have couple of colleagues that would also join in on the translation. For now, it will be only me, but they will join shortly after we establish the repository.

Github nick: dotundefined
E-mail: mustaficjasmin7@gmail.com

**Comment by iliakan** [comment]
Great! Please take over the translation @dejansdev @dotundefined  ;)

**Comment by dotundefined** [comment]
Cheers @iliakan. Thank you for the invite. :)

I will have some questions coming up, regarding some PRs and repo management.

**Comment by ismi4** [comment]
Hi @iliakan. :) I am also willing to give my contribution to Bosnian translation.

Github nick: ismi4
E-mail: brkicismail@gmail.com

Thank you! :D

**Comment by iliakan** [comment]
@ismi4 you can! Create a PR, let others review it. If you're proficient in JS and can review PRs of others, I can grant you the maintainer status.
