### ISSUE TITLE
Missing "return" keyword in sort-objects solution

### ISSUE THREAD

**Issue by victoriacheng15** [javascript-tutorial/en.javascript.info#2965]
This function misses the `return` keyword.

The solution.md is located [data types -> array methods -> sort-objects](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/05-array-methods/8-sort-objects/solution.md).

```js
function sortByAge(arr) {
  arr.sort((a, b) => a.age - b.age);
}
```

It should be:

```js
function sortByAge(arr) {
  return arr.sort((a, b) => a.age - b.age);
}
```

**Comment by victoriacheng15** [comment]
I originally used `console.log(sortByAge(arr));` to see the sorted array, and got a result of `undefined`. Which is why I thought the function needs `return` there. 

I just played around with the solution again. If I do this way as the code block shows, `console.log` will return the sorted array. I didn't realize this way works as well. I learned something new today.
```js
sortByAge(arr);
console.log(arr);
```

Anyway, thank you for quick respond and cleared up any confusions. 😊

**Comment by victoriacheng15** [comment]
Issue is resolved!

**Comment by joaquinelio** [comment]
I dont know if the return must be there (right: no need) 
but

You should ask why consle.log( sortByAge(... didnt work
ok, it works by altering the argument. It's dirty. So is arr.sort, but arr.sort returns something, because one EXPECTS it to.

so adding a return value would be, at least, polite.

Later in the tutorial you see the power of chaining, this gives you a reason to return what's expected
