### ISSUE TITLE
Hindi Translation

### ISSUE THREAD

**Issue by siradityaverma** [javascript-tutorial/en.javascript.info#641]
https://github.com/siradityaverma/javascript-tutorial-hi

Hi, started working on the Hindi Translation. Will update you once I reach the desirable translation required to get listed. 👍

**Comment by iliakan** [comment]
I guess, the translation is dead?

**Comment by siradityaverma** [comment]
no no, I am having hectic months in my office. I will commit the changes after 25th January. So sorry about the inactivity

**Comment by iliakan** [comment]
Ok, great, thanks for the update!

**Comment by iliakan** [comment]
Hello @siradityaverma  !

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by siradityaverma** [comment]
Do you want me to transfer the ownership to you?

**Comment by iliakan** [comment]
Transfer to @iliakan, and I will transfer to the org.

All permissions, authors etc will remain as is.

**Comment by siradityaverma** [comment]
@iliakan sent a transfer request to you.

**Comment by iliakan** [comment]
Oops! That repository transfer has expired.

**Comment by siradityaverma** [comment]
It expired because you accepted transfer link. Opening the link above redirects to a project under your username.

**Comment by iliakan** [comment]
Oh, sorry then. Usually, when it transfers, there's another message. Probably, the page refreshed.

Hindi translation is very important for us, there are many people from India.
I will setup the Hindi repo ASAP.

**Comment by iliakan** [comment]
1. Created https://github.com/javascript-tutorial/hi.javascript.info, loaded it with your content. Didn't move the repo, just duplicated it. I hope it's ok.
2. Added new `Readme.md` to it, better than the old one. Your translation is in the previous commit, so you can copy the same stuff from it =)
3. Created PR to sync changes from the English version. Readme.md is irrelevant (your have your own), translation.md is deleted.
