### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by longo-andrea** [javascript-tutorial/en.javascript.info#651]
Hi, I started working on the Italian Translation. 
I will try to give you the best translation based on Italian language.

I will work roughly once a day, if I can. 
Unfortunately, towards January I could have some commitments.

https://github.com/longo-andrea/javascript-tutorial-it

**Comment by dcop** [comment]
Hi Andrea, 

I can help. Which chapters have already been translated? 
I think the best way to work is to clone your repo and open PR there, unless you have a better idea.

Let me know.

**Comment by longo-andrea** [comment]
Hi Daniele,
I have already translated chapter 1 - "js" until sub-chapters 2 "first-steps".
For the transaltion,I used to left all examples in english included comments(I'm thinking about translating these one). 
In order to avoid working on the same chapters you can translate the odd ones(except "Getting Started").
I also think the best way is to clone my repo.

**Comment by iliakan** [comment]
Maybe use Pull Requests to integrate translations? 

To avoid working on same chapters, maybe @dcop could work on Part 2?

**Comment by dcop** [comment]
@longo-andrea I'm gonna take @iliakan road and start with Chapter 2 (UI) and the even Chapters after that since you're doing Chapter 1 (JS). I think it might be better this way.

I agree with you about leaving examples untranslated, at least for now. In case we change our mind we can always do that later.

**Comment by longo-andrea** [comment]
I'm not very experienced with git, so I follow your suggestion.

**Comment by iliakan** [comment]
How goes? I guess, there's a lot translated already, so that I could add that to the Readme file?

**Comment by longo-andrea** [comment]
I have almost finished the big of introduction, but in the next 2-3 weeks I will be a little bit busy with college.
I expect to finish the first chapter about half of February.
The last commit of @dcop is about one month ago, so I don't know if he still working on translation.

**Comment by dcop** [comment]
I'm sorry guys, but personal stuff got in the way of translation and things slowed down a little. I don't think I'll be able to keep translating anytime soon.
I've created a PR on @longo-andrea fork with the articles translated so far.

**Comment by longo-andrea** [comment]
May I had misjudge the lenght of JS chapter, so I think I can't end it before end of February, but I still working at full rhytm on it.
So if you want to add Italian transaltion to list.
Then I took a look to UI and Animation chapter, and I think I can be able to end either for the end of March.

**Comment by iliakan** [comment]
Hello @longo-andrea and others!

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by fzancan** [comment]
Hello @longo-andrea and others, I could help with the Italian translation; can somebody point me towards the steps to get the repo and what part of the material I'd better work upon?

**Comment by longo-andrea** [comment]
Hi @iliakan, go ahead with the first variant.

Hello @fzancan, you can fork the repo from the link i left up on the first comment, then you can work on the even's chapters (ui, frames-and-windows, ecc...).

**Comment by iliakan** [comment]
Ok, all PRs and issues will not travel to the new repo then @longo-andrea

**Comment by iliakan** [comment]
Here's new repo, https://github.com/javascript-tutorial/it.javascript.info
Please archive the old one, so that people don't occasionally commit to it =)
