### ISSUE TITLE
Translate into Thai

### ISSUE THREAD

**Issue by EpicHigh** [javascript-tutorial/en.javascript.info#700]
Merry Chrismas and Happy New Year

Your project is really awesome. I just started to kick off your project into Thai translation.
https://github.com/EpicHigh/javascript-tutorial-th

If you have any issue, Pleases let me know.

PS. I will contact you very soon about setting it up live online.

**Comment by iliakan** [comment]
Great, let me know when some articles are finished, so that I can add it to the list.

**Comment by iliakan** [comment]
How goes? :)

**Comment by EpicHigh** [comment]
Just getting started chapter was finished.

**Comment by iliakan** [comment]
Hello @EpicHigh  !

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by iliakan** [comment]
Closing as inactive.

**Comment by iliakan** [comment]
Moved translation to https://github.com/javascript-tutorial/th.javascript.info
