### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by henriquezanfa** [javascript-tutorial/en.javascript.info#751]
https://github.com/henriquezanfa/javascript-tutorial-pt

**Comment by iliakan** [comment]
Please note, there were attempts already to translate into Portuguese: https://github.com/iliakan/javascript-tutorial-en/issues?utf8=%E2%9C%93&q=is%3Aissue+portugal+

Maybe it's worth to take what's done into your repo and continue from that.

Let me know when something is translated.

**Comment by henriquezanfa** [comment]
Nothing was really done in any of this attempts unfortunately. The one that seems to have something was translated with an automatic translator, I gess, cause it is kind of weird... I started the intrp. Maybe something like 20% of it (almost nothing) is in portuguese.

**Comment by iliakan** [comment]
Hello @henriquezanfa !

I see you managed to translate something?

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by henriquezanfa** [comment]
Hello @iliakan !

It's ok to just clone-reimport the repo.

**Comment by iliakan** [comment]
It seems, you did not clone the English repository, but created a completely new one, with unrelated history. For that reason, new scripts that auto-sync English changes into the translation, won't work.

I created a new repo https://github.com/javascript-tutorial/pt-PT.javascript.info, that is a proper fork.

Please move your translations to it, and we'll continue on with the scripts working :)

Thank you!

**Comment by iliakan** [comment]
@henriquezanfa and maybe after that archive the old repo, so that no one accidentally commits to it.

**Comment by iliakan** [comment]
Closing this, as the repository has its own progress issue now.

**Comment by iliakan** [comment]
When I look at Wikipedia, there's only pt.wikipedia.org.

Does it really make sense to have separate pt-br.javascript.info and pt-pt.javascript.info? Or we can join the efforts to have just pt.javascript.info?

**Comment by iliakan** [comment]
@henriquezanfa
