### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by lizzie136** [javascript-tutorial/en.javascript.info#754]
Hello @iliakan! Time ago I contact you to start this project. Finally, I can get through this with some other people. 
This is the repository https://github.com/lizzie136/javacript-tutorial-es

Can you include it in the list, I'll be updating it as soon as possible. 

Thanks!! 

Elizabeth

**Comment by iliakan** [comment]
Maybe you'd want to pickup what's done in the abandoned translation https://github.com/lmauromb/javascript-tutorial-es?

**Comment by lizzie136** [comment]
I don’t think so. It does not have any translation updated to that repository. Do you mind if I start this one with the people that would be part of the team?

**Comment by lizzie136** [comment]
Thanks!

**Comment by caballerof** [comment]
I would like to help with the Spanish translation, what could I do?.
Do I to start my own copy of the repository or ask for permission into the @lizzie136 copy?

**Comment by iliakan** [comment]
@lizzie136 how about to give @caballerof access and let him translate the 2nd part while you translate the 1st?

**Comment by lizzie136** [comment]
@caballerof , I invited you to the repo. If you prefer, to have a fork and sent PR is cool too :D

**Comment by caballerof** [comment]
I made my own Fork, such as @lizzie136 recommended me, I just translated the first file and I made a pull request to @lizzie136 's repo.

Do you think it is a good work process?

**Comment by victorze** [comment]
Because the translation into Spanish is not progressing, I decided to create a new [repository](https://github.com/victorze-forks/javascript-tutorial-es) to work on the translation.

**Comment by iliakan** [comment]
@caballerof  @lizzie136 is your work really stalled, so it makes sense to create a new repo?

**Comment by lizzie136** [comment]
not really, we are working on it, you can sent us a PR @victorze :)

**Comment by victorze** [comment]
Ok @lizzie136, I'm going to translate part 2.

**Comment by maurodibert** [comment]
Hi people! @iliakan told me about this since I want to translate the tutorial for the free Code Camp community Argentina. Can I join you?

**Comment by lizzie136** [comment]
Hello @maurodibert !! Totally! you can join us [here at discord ](https://discord.gg/AH2CND) so we could coordinate the chapters and don't repeat ourselves

**Comment by tscandalitta** [comment]
Hey, I'd like to help. How is the translation going?

**Comment by lizzie136** [comment]
Hi  @tscandalitta  kind of stalled the last week, but you are totally welcome :D

**Comment by iliakan** [comment]
Hello @lizzie136 and others!

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by lizzie136** [comment]
Hello @iliakan, I'll try to transfer it and I'll get back to you.

**Comment by lizzie136** [comment]
@iliakan I tried to transfer it but it says: `You don’t have the permission to create repositories on javascript-tutorial` 
Can I transfer it to you and you change it to the organization?

**Comment by iliakan** [comment]
Please transfer to @iliakan, I'll move along. Thanks!

**Comment by iliakan** [comment]
Closing this, as the repository has its own progress issue now.
