### ISSUE TITLE
Ukrainian Translation

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/en.javascript.info#891]
Hi.
**Ukrainian** translation is going here: https://github.com/tarasyyyk/javascript-tutorial-uk.
Just created issue to let you know (and other contributors) the translation into Ukrainian language in progress.
Last commit to this repo was made: ![](https://img.shields.io/github/last-commit/tarasyyyk/javascript-tutorial-uk.svg?maxAge=900&label=)

I have one question about translation. Can I also change the links of Wikipedia to corresponding translated pages?
For example: from https://en.wikipedia.org/wiki/SpiderMonkey to https://uk.wikipedia.org/wiki/SpiderMonkey

**Comment by iliakan** [comment]
Let me know when you progress enough.
Yes, link to Ukrainian where possible.

**Comment by iliakan** [comment]
Is everything ok? Let me know how it goes. If you changed your mind, please close the issue.

**Comment by tarasyyyk** [comment]
@iliakan I'll tell you when will be progress

**Comment by iliakan** [comment]
Hello @tarasyyyk  !

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by tarasyyyk** [comment]
Hi @iliakan . I hadn't any issues on my repo so the first variant is preferable.
You can copy my repo to this org.

**Comment by iliakan** [comment]
Done! https://github.com/javascript-tutorial/uk.javascript.info
